### ISSUE TITLE
aarch64 compiling

### ISSUE THREAD

**Issue by Mila432** [swigger/gdb-ios#1]
configure: error: "**\* Gdb does not support native target aarch64-arm-darwin"

any help ?

**Comment by swigger** [comment]
I missed a file. I added it seconds ago. Try again.

**Comment by Mila432** [comment]
solib-darwin.c:603:39: error: incompatible pointer types passing 'CORE_ADDR *' (aka 'unsigned long *') to parameter of type 'uint64_t *' (aka 'unsigned long long *') [-Werror,-Wincompatible-pointer-types](*darwin_adjust_image_notifier)(& info->all_image.notifier);

how did you compile it ?
maybe you can contact me under gdb[at]mila432.xyz

**Comment by swigger** [comment]
unsigned long on gcc/aarch64 is 64bits , same as uint64_t . so this warning can be ignored. My toolchain just removed the -Werror option. Sorry I have no time to full fix issues like this. And this project is still not stable. May be you can fork and go further.

**Comment by swigger** [comment]
Uploaded my just-working toolchain.
