### ISSUE TITLE
Actual example of toolchain setup

### ISSUE THREAD

**Issue by jessesanford** [swigger/gdb-ios#2]
Can you provide the shell script you use to setup the toolchain?

**Comment by swigger** [comment]
OK,  I will put it on github when I have free time.

**Comment by Lars-Delphi** [comment]
Where can I find the script? 

If I want to build (--build=aarch64-arm-darwin) your project I get this ERROR:
solib-darwin.c:603:39: error: incompatible pointer types passing 'CORE_ADDR *' (aka 'unsigned long *') to parameter of type 'uint64_t *' (aka 'unsigned long long *') -Werror,-Wincompatible-pointer-types(& info->all_image.notifier);

if I set  --host=aarch64-arm-darwin I get this ERROR:
make[2]: aarch64-arm-darwin-ar: No such file or directory
make[2]: *** [libiberty.a] Error 1
make[1]: *** [all-libiberty] Error 2
make: *** [all] Error 2

**Comment by swigger** [comment]
I have uploaded my experimental toolchain.
